// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `ggwi.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __ggwi_h__
#define __ggwi_h__

#include <gns_api_raii.h>
#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace GGW
{

class GGWQueue;

}

}

namespace GGW
{

class GGWQueue;
bool operator==(const GGWQueue&, const GGWQueue&);
bool operator<(const GGWQueue&, const GGWQueue&);

}

namespace IceInternal
{

::Ice::Object* upCast(::GGW::GGWQueue*);
::IceProxy::Ice::Object* upCast(::IceProxy::GGW::GGWQueue*);

}

namespace GGW
{

typedef ::IceInternal::Handle< ::GGW::GGWQueue> GGWQueuePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::GGW::GGWQueue> GGWQueuePrx;

void __read(::IceInternal::BasicStream*, GGWQueuePrx&);
void __patch__GGWQueuePtr(void*, ::Ice::ObjectPtr&);

}

namespace GGW
{

typedef ::std::vector< ::Ice::Byte> Line;

typedef ::std::vector< ::GGW::Line> Table;
void __writeTable(::IceInternal::BasicStream*, const ::GGW::Line*, const ::GGW::Line*);
void __readTable(::IceInternal::BasicStream*, Table&);

typedef ::std::vector< ::std::string> StrSeq;

}

namespace GGW
{

class Callback_GGWQueue_writeMessages_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GGWQueue_writeMessages_Base> Callback_GGWQueue_writeMessagesPtr;

class Callback_GGWQueue_readMessages_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GGWQueue_readMessages_Base> Callback_GGWQueue_readMessagesPtr;

class Callback_GGWQueue_readMessagesAck_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GGWQueue_readMessagesAck_Base> Callback_GGWQueue_readMessagesAckPtr;

class Callback_GGWQueue_addQueue_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GGWQueue_addQueue_Base> Callback_GGWQueue_addQueuePtr;

class Callback_GGWQueue_removeQueue_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GGWQueue_removeQueue_Base> Callback_GGWQueue_removeQueuePtr;

class Callback_GGWQueue_getGmqStatus_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GGWQueue_getGmqStatus_Base> Callback_GGWQueue_getGmqStatusPtr;

class Callback_GGWQueue_setGmqStatus_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GGWQueue_setGmqStatus_Base> Callback_GGWQueue_setGmqStatusPtr;

}

namespace IceProxy
{

namespace GGW
{

class GGWQueue : virtual public ::IceProxy::Ice::Object
{
public:

    void writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& content)
    {
        writeMessages(content, 0);
    }
    void writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& content, const ::Ice::Context& __ctx)
    {
        writeMessages(content, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& content)
    {
        return begin_writeMessages(content, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& content, const ::Ice::Context& __ctx)
    {
        return begin_writeMessages(content, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& content, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_writeMessages(content, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& content, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_writeMessages(content, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& content, const ::GGW::Callback_GGWQueue_writeMessagesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_writeMessages(content, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& content, const ::Ice::Context& __ctx, const ::GGW::Callback_GGWQueue_writeMessagesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_writeMessages(content, &__ctx, __del, __cookie);
    }

    void end_writeMessages(const ::Ice::AsyncResultPtr&);
    
private:

    void writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Long readMessages(const ::std::string& queue, ::GGW::Table& tbl)
    {
        return readMessages(queue, tbl, 0);
    }
    ::Ice::Long readMessages(const ::std::string& queue, ::GGW::Table& tbl, const ::Ice::Context& __ctx)
    {
        return readMessages(queue, tbl, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_readMessages(const ::std::string& queue)
    {
        return begin_readMessages(queue, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_readMessages(const ::std::string& queue, const ::Ice::Context& __ctx)
    {
        return begin_readMessages(queue, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_readMessages(const ::std::string& queue, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_readMessages(queue, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_readMessages(const ::std::string& queue, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_readMessages(queue, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_readMessages(const ::std::string& queue, const ::GGW::Callback_GGWQueue_readMessagesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_readMessages(queue, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_readMessages(const ::std::string& queue, const ::Ice::Context& __ctx, const ::GGW::Callback_GGWQueue_readMessagesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_readMessages(queue, &__ctx, __del, __cookie);
    }

    ::Ice::Long end_readMessages(::GGW::Table& tbl, const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Long readMessages(const ::std::string&, ::GGW::Table&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_readMessages(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void readMessagesAck(const ::std::string& queue, ::Ice::Long seq)
    {
        readMessagesAck(queue, seq, 0);
    }
    void readMessagesAck(const ::std::string& queue, ::Ice::Long seq, const ::Ice::Context& __ctx)
    {
        readMessagesAck(queue, seq, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_readMessagesAck(const ::std::string& queue, ::Ice::Long seq)
    {
        return begin_readMessagesAck(queue, seq, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_readMessagesAck(const ::std::string& queue, ::Ice::Long seq, const ::Ice::Context& __ctx)
    {
        return begin_readMessagesAck(queue, seq, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_readMessagesAck(const ::std::string& queue, ::Ice::Long seq, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_readMessagesAck(queue, seq, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_readMessagesAck(const ::std::string& queue, ::Ice::Long seq, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_readMessagesAck(queue, seq, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_readMessagesAck(const ::std::string& queue, ::Ice::Long seq, const ::GGW::Callback_GGWQueue_readMessagesAckPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_readMessagesAck(queue, seq, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_readMessagesAck(const ::std::string& queue, ::Ice::Long seq, const ::Ice::Context& __ctx, const ::GGW::Callback_GGWQueue_readMessagesAckPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_readMessagesAck(queue, seq, &__ctx, __del, __cookie);
    }

    void end_readMessagesAck(const ::Ice::AsyncResultPtr&);
    
private:

    void readMessagesAck(const ::std::string&, ::Ice::Long, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_readMessagesAck(const ::std::string&, ::Ice::Long, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    bool addQueue(const ::std::string& queue)
    {
        return addQueue(queue, 0);
    }
    bool addQueue(const ::std::string& queue, const ::Ice::Context& __ctx)
    {
        return addQueue(queue, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_addQueue(const ::std::string& queue)
    {
        return begin_addQueue(queue, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addQueue(const ::std::string& queue, const ::Ice::Context& __ctx)
    {
        return begin_addQueue(queue, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addQueue(const ::std::string& queue, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addQueue(queue, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addQueue(const ::std::string& queue, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addQueue(queue, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addQueue(const ::std::string& queue, const ::GGW::Callback_GGWQueue_addQueuePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addQueue(queue, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addQueue(const ::std::string& queue, const ::Ice::Context& __ctx, const ::GGW::Callback_GGWQueue_addQueuePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addQueue(queue, &__ctx, __del, __cookie);
    }

    bool end_addQueue(const ::Ice::AsyncResultPtr&);
    
private:

    bool addQueue(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_addQueue(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    bool removeQueue(const ::std::string& queue)
    {
        return removeQueue(queue, 0);
    }
    bool removeQueue(const ::std::string& queue, const ::Ice::Context& __ctx)
    {
        return removeQueue(queue, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_removeQueue(const ::std::string& queue)
    {
        return begin_removeQueue(queue, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_removeQueue(const ::std::string& queue, const ::Ice::Context& __ctx)
    {
        return begin_removeQueue(queue, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_removeQueue(const ::std::string& queue, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_removeQueue(queue, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_removeQueue(const ::std::string& queue, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_removeQueue(queue, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_removeQueue(const ::std::string& queue, const ::GGW::Callback_GGWQueue_removeQueuePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_removeQueue(queue, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_removeQueue(const ::std::string& queue, const ::Ice::Context& __ctx, const ::GGW::Callback_GGWQueue_removeQueuePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_removeQueue(queue, &__ctx, __del, __cookie);
    }

    bool end_removeQueue(const ::Ice::AsyncResultPtr&);
    
private:

    bool removeQueue(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_removeQueue(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void getGmqStatus(::GGW::StrSeq& status)
    {
        getGmqStatus(status, 0);
    }
    void getGmqStatus(::GGW::StrSeq& status, const ::Ice::Context& __ctx)
    {
        getGmqStatus(status, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_getGmqStatus()
    {
        return begin_getGmqStatus(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getGmqStatus(const ::Ice::Context& __ctx)
    {
        return begin_getGmqStatus(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getGmqStatus(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getGmqStatus(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getGmqStatus(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getGmqStatus(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getGmqStatus(const ::GGW::Callback_GGWQueue_getGmqStatusPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getGmqStatus(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getGmqStatus(const ::Ice::Context& __ctx, const ::GGW::Callback_GGWQueue_getGmqStatusPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getGmqStatus(&__ctx, __del, __cookie);
    }

    void end_getGmqStatus(::GGW::StrSeq& status, const ::Ice::AsyncResultPtr&);
    
private:

    void getGmqStatus(::GGW::StrSeq&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getGmqStatus(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setGmqStatus(const ::GGW::StrSeq& status)
    {
        setGmqStatus(status, 0);
    }
    void setGmqStatus(const ::GGW::StrSeq& status, const ::Ice::Context& __ctx)
    {
        setGmqStatus(status, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_setGmqStatus(const ::GGW::StrSeq& status)
    {
        return begin_setGmqStatus(status, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setGmqStatus(const ::GGW::StrSeq& status, const ::Ice::Context& __ctx)
    {
        return begin_setGmqStatus(status, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setGmqStatus(const ::GGW::StrSeq& status, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setGmqStatus(status, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setGmqStatus(const ::GGW::StrSeq& status, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setGmqStatus(status, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setGmqStatus(const ::GGW::StrSeq& status, const ::GGW::Callback_GGWQueue_setGmqStatusPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setGmqStatus(status, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setGmqStatus(const ::GGW::StrSeq& status, const ::Ice::Context& __ctx, const ::GGW::Callback_GGWQueue_setGmqStatusPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setGmqStatus(status, &__ctx, __del, __cookie);
    }

    void end_setGmqStatus(const ::Ice::AsyncResultPtr&);
    
private:

    void setGmqStatus(const ::GGW::StrSeq&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setGmqStatus(const ::GGW::StrSeq&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<GGWQueue> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<GGWQueue*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<GGWQueue*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

public: 

    GNS_API::CALLER m_caller;

    GNS_API::CALLEE m_callee;

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace GGW
{

class GGWQueue : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const ::Ice::Context*) = 0;

    virtual ::Ice::Long readMessages(const ::std::string&, ::GGW::Table&, const ::Ice::Context*) = 0;

    virtual void readMessagesAck(const ::std::string&, ::Ice::Long, const ::Ice::Context*) = 0;

    virtual bool addQueue(const ::std::string&, const ::Ice::Context*) = 0;

    virtual bool removeQueue(const ::std::string&, const ::Ice::Context*) = 0;

    virtual void getGmqStatus(::GGW::StrSeq&, const ::Ice::Context*) = 0;

    virtual void setGmqStatus(const ::GGW::StrSeq&, const ::Ice::Context*) = 0;
};

}

}

namespace IceDelegateM
{

namespace GGW
{

class GGWQueue : virtual public ::IceDelegate::GGW::GGWQueue,
                 virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const ::Ice::Context*);

    virtual ::Ice::Long readMessages(const ::std::string&, ::GGW::Table&, const ::Ice::Context*);

    virtual void readMessagesAck(const ::std::string&, ::Ice::Long, const ::Ice::Context*);

    virtual bool addQueue(const ::std::string&, const ::Ice::Context*);

    virtual bool removeQueue(const ::std::string&, const ::Ice::Context*);

    virtual void getGmqStatus(::GGW::StrSeq&, const ::Ice::Context*);

    virtual void setGmqStatus(const ::GGW::StrSeq&, const ::Ice::Context*);
};

}

}

namespace IceDelegateD
{

namespace GGW
{

class GGWQueue : virtual public ::IceDelegate::GGW::GGWQueue,
                 virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const ::Ice::Context*);

    virtual ::Ice::Long readMessages(const ::std::string&, ::GGW::Table&, const ::Ice::Context*);

    virtual void readMessagesAck(const ::std::string&, ::Ice::Long, const ::Ice::Context*);

    virtual bool addQueue(const ::std::string&, const ::Ice::Context*);

    virtual bool removeQueue(const ::std::string&, const ::Ice::Context*);

    virtual void getGmqStatus(::GGW::StrSeq&, const ::Ice::Context*);

    virtual void setGmqStatus(const ::GGW::StrSeq&, const ::Ice::Context*);
};

}

}

namespace GGW
{

class GGWQueue : virtual public ::Ice::Object
{
public:

    typedef GGWQueuePrx ProxyType;
    typedef GGWQueuePtr PointerType;
    
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void writeMessages(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___writeMessages(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Long readMessages(const ::std::string&, ::GGW::Table&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___readMessages(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void readMessagesAck(const ::std::string&, ::Ice::Long, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___readMessagesAck(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool addQueue(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___addQueue(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool removeQueue(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___removeQueue(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void getGmqStatus(::GGW::StrSeq&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getGmqStatus(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setGmqStatus(const ::GGW::StrSeq&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setGmqStatus(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif
};

inline bool operator==(const GGWQueue& l, const GGWQueue& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const GGWQueue& l, const GGWQueue& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace GGW
{

template<class T>
class CallbackNC_GGWQueue_writeMessages : public Callback_GGWQueue_writeMessages_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_GGWQueue_writeMessages(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_GGWQueue_writeMessagesPtr
newCallback_GGWQueue_writeMessages(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_writeMessages<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GGWQueue_writeMessagesPtr
newCallback_GGWQueue_writeMessages(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_writeMessages<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_GGWQueue_writeMessagesPtr
newCallback_GGWQueue_writeMessages(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_writeMessages<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GGWQueue_writeMessagesPtr
newCallback_GGWQueue_writeMessages(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_writeMessages<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_GGWQueue_writeMessages : public Callback_GGWQueue_writeMessages_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_GGWQueue_writeMessages(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_GGWQueue_writeMessagesPtr
newCallback_GGWQueue_writeMessages(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_writeMessages<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GGWQueue_writeMessagesPtr
newCallback_GGWQueue_writeMessages(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_writeMessages<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_GGWQueue_writeMessagesPtr
newCallback_GGWQueue_writeMessages(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_writeMessages<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GGWQueue_writeMessagesPtr
newCallback_GGWQueue_writeMessages(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_writeMessages<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_GGWQueue_readMessages : public Callback_GGWQueue_readMessages_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Long, const ::GGW::Table&);

    CallbackNC_GGWQueue_readMessages(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::GGW::GGWQueuePrx __proxy = ::GGW::GGWQueuePrx::uncheckedCast(__result->getProxy());
        ::GGW::Table tbl;
        ::Ice::Long __ret;
        try
        {
            __ret = __proxy->end_readMessages(tbl, __result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, tbl);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret, tbl);
#endif
        }
    }

    Response response;
};

template<class T> Callback_GGWQueue_readMessagesPtr
newCallback_GGWQueue_readMessages(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Long, const ::GGW::Table&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_readMessages<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GGWQueue_readMessagesPtr
newCallback_GGWQueue_readMessages(T* instance, void (T::*cb)(::Ice::Long, const ::GGW::Table&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_readMessages<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_GGWQueue_readMessages : public Callback_GGWQueue_readMessages_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Long, const ::GGW::Table&, const CT&);

    Callback_GGWQueue_readMessages(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::GGW::GGWQueuePrx __proxy = ::GGW::GGWQueuePrx::uncheckedCast(__result->getProxy());
        ::GGW::Table tbl;
        ::Ice::Long __ret;
        try
        {
            __ret = __proxy->end_readMessages(tbl, __result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, tbl, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, tbl, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_GGWQueue_readMessagesPtr
newCallback_GGWQueue_readMessages(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Long, const ::GGW::Table&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_readMessages<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GGWQueue_readMessagesPtr
newCallback_GGWQueue_readMessages(T* instance, void (T::*cb)(::Ice::Long, const ::GGW::Table&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_readMessages<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_GGWQueue_readMessagesAck : public Callback_GGWQueue_readMessagesAck_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_GGWQueue_readMessagesAck(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_GGWQueue_readMessagesAckPtr
newCallback_GGWQueue_readMessagesAck(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_readMessagesAck<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GGWQueue_readMessagesAckPtr
newCallback_GGWQueue_readMessagesAck(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_readMessagesAck<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_GGWQueue_readMessagesAckPtr
newCallback_GGWQueue_readMessagesAck(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_readMessagesAck<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GGWQueue_readMessagesAckPtr
newCallback_GGWQueue_readMessagesAck(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_readMessagesAck<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_GGWQueue_readMessagesAck : public Callback_GGWQueue_readMessagesAck_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_GGWQueue_readMessagesAck(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_GGWQueue_readMessagesAckPtr
newCallback_GGWQueue_readMessagesAck(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_readMessagesAck<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GGWQueue_readMessagesAckPtr
newCallback_GGWQueue_readMessagesAck(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_readMessagesAck<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_GGWQueue_readMessagesAckPtr
newCallback_GGWQueue_readMessagesAck(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_readMessagesAck<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GGWQueue_readMessagesAckPtr
newCallback_GGWQueue_readMessagesAck(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_readMessagesAck<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_GGWQueue_addQueue : public Callback_GGWQueue_addQueue_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_GGWQueue_addQueue(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::GGW::GGWQueuePrx __proxy = ::GGW::GGWQueuePrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_addQueue(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_GGWQueue_addQueuePtr
newCallback_GGWQueue_addQueue(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_addQueue<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GGWQueue_addQueuePtr
newCallback_GGWQueue_addQueue(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_addQueue<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_GGWQueue_addQueue : public Callback_GGWQueue_addQueue_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_GGWQueue_addQueue(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::GGW::GGWQueuePrx __proxy = ::GGW::GGWQueuePrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_addQueue(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_GGWQueue_addQueuePtr
newCallback_GGWQueue_addQueue(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_addQueue<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GGWQueue_addQueuePtr
newCallback_GGWQueue_addQueue(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_addQueue<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_GGWQueue_removeQueue : public Callback_GGWQueue_removeQueue_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_GGWQueue_removeQueue(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::GGW::GGWQueuePrx __proxy = ::GGW::GGWQueuePrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_removeQueue(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_GGWQueue_removeQueuePtr
newCallback_GGWQueue_removeQueue(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_removeQueue<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GGWQueue_removeQueuePtr
newCallback_GGWQueue_removeQueue(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_removeQueue<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_GGWQueue_removeQueue : public Callback_GGWQueue_removeQueue_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_GGWQueue_removeQueue(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::GGW::GGWQueuePrx __proxy = ::GGW::GGWQueuePrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_removeQueue(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_GGWQueue_removeQueuePtr
newCallback_GGWQueue_removeQueue(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_removeQueue<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GGWQueue_removeQueuePtr
newCallback_GGWQueue_removeQueue(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_removeQueue<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_GGWQueue_getGmqStatus : public Callback_GGWQueue_getGmqStatus_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::GGW::StrSeq&);

    CallbackNC_GGWQueue_getGmqStatus(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::GGW::GGWQueuePrx __proxy = ::GGW::GGWQueuePrx::uncheckedCast(__result->getProxy());
        ::GGW::StrSeq status;
        try
        {
            __proxy->end_getGmqStatus(status, __result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(status);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(status);
#endif
        }
    }

    Response response;
};

template<class T> Callback_GGWQueue_getGmqStatusPtr
newCallback_GGWQueue_getGmqStatus(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::GGW::StrSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_getGmqStatus<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GGWQueue_getGmqStatusPtr
newCallback_GGWQueue_getGmqStatus(T* instance, void (T::*cb)(const ::GGW::StrSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_getGmqStatus<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_GGWQueue_getGmqStatus : public Callback_GGWQueue_getGmqStatus_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::GGW::StrSeq&, const CT&);

    Callback_GGWQueue_getGmqStatus(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::GGW::GGWQueuePrx __proxy = ::GGW::GGWQueuePrx::uncheckedCast(__result->getProxy());
        ::GGW::StrSeq status;
        try
        {
            __proxy->end_getGmqStatus(status, __result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(status, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(status, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_GGWQueue_getGmqStatusPtr
newCallback_GGWQueue_getGmqStatus(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::GGW::StrSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_getGmqStatus<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GGWQueue_getGmqStatusPtr
newCallback_GGWQueue_getGmqStatus(T* instance, void (T::*cb)(const ::GGW::StrSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_getGmqStatus<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_GGWQueue_setGmqStatus : public Callback_GGWQueue_setGmqStatus_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_GGWQueue_setGmqStatus(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_GGWQueue_setGmqStatusPtr
newCallback_GGWQueue_setGmqStatus(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_setGmqStatus<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GGWQueue_setGmqStatusPtr
newCallback_GGWQueue_setGmqStatus(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_setGmqStatus<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_GGWQueue_setGmqStatusPtr
newCallback_GGWQueue_setGmqStatus(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_setGmqStatus<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GGWQueue_setGmqStatusPtr
newCallback_GGWQueue_setGmqStatus(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GGWQueue_setGmqStatus<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_GGWQueue_setGmqStatus : public Callback_GGWQueue_setGmqStatus_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_GGWQueue_setGmqStatus(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_GGWQueue_setGmqStatusPtr
newCallback_GGWQueue_setGmqStatus(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_setGmqStatus<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GGWQueue_setGmqStatusPtr
newCallback_GGWQueue_setGmqStatus(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_setGmqStatus<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_GGWQueue_setGmqStatusPtr
newCallback_GGWQueue_setGmqStatus(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_setGmqStatus<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GGWQueue_setGmqStatusPtr
newCallback_GGWQueue_setGmqStatus(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GGWQueue_setGmqStatus<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
