# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import customer_tree_pb2 as customer__tree__pb2


class CTreeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getCustomInfo = channel.unary_unary(
        '/customer_tree.CTree/getCustomInfo',
        request_serializer=customer__tree__pb2.CustomerInfo.SerializeToString,
        response_deserializer=customer__tree__pb2.CustomerInfo.FromString,
        )
    self.getChildrenInfo = channel.unary_stream(
        '/customer_tree.CTree/getChildrenInfo',
        request_serializer=customer__tree__pb2.CustomerInfo.SerializeToString,
        response_deserializer=customer__tree__pb2.CustomerInfo.FromString,
        )


class CTreeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getCustomInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getChildrenInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CTreeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getCustomInfo': grpc.unary_unary_rpc_method_handler(
          servicer.getCustomInfo,
          request_deserializer=customer__tree__pb2.CustomerInfo.FromString,
          response_serializer=customer__tree__pb2.CustomerInfo.SerializeToString,
      ),
      'getChildrenInfo': grpc.unary_stream_rpc_method_handler(
          servicer.getChildrenInfo,
          request_deserializer=customer__tree__pb2.CustomerInfo.FromString,
          response_serializer=customer__tree__pb2.CustomerInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'customer_tree.CTree', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
